insert into customer (customer_id, email, first_name, last_name, site_id)values (1000, 'test@gmail.com', 'Joe', 'Roy', 'ftd')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1001, 'test1@gmail.com', 'Kio', 'Kom', 'ftd')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1002, 'test2@gmail.com', 'Ken', 'Dat', 'ftd')
insert into address (customer_id, address_id, street_address, address1, city) values (1000, 10000, 'Cyber Gateway', 'Madhapur', 'Hyderabad')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1003, 'test3@gmail.com', 'Ken', 'Dat', 'ftd')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1004, 'test4@gmail.com', 'Ken', 'Dat', 'ftd')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1005, 'test5@gmail.com', 'Ken', 'Dat', 'ftd')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1006, 'test6@gmail.com', 'Ken', 'Dat', 'ftd')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1007, 'test7@gmail.com', 'Ken', 'Dat', 'ftd')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1008, 'test8@gmail.com', 'Ken', 'Dat', 'ftd')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1009, 'test09@gmail.com', 'Ken', 'Dat', 'ftd')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1010, 'test10@gmail.com', 'Ken', 'Dat', 'proflowers')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1011, 'test11@gmail.com', 'Ken', 'Dat', 'proflowers')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1012, 'test12@gmail.com', 'Ken', 'Dat', 'proflowers')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1013, 'test13@gmail.com', 'Ken', 'Dat', 'proflowers')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1014, 'test14@gmail.com', 'Ken', 'Dat', 'proflowers')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1015, 'test15@gmail.com', 'Ken', 'Dat', 'proflowers')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1016, 'test16@gmail.com', 'Ken', 'Dat', 'proflowers')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1017, 'test17@gmail.com', 'Ken', 'Dat', 'proflowers')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1018, 'test18@gmail.com', 'Ken', 'Dat', 'proflowers')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1019, 'test19@gmail.com', 'Ken', 'Dat', 'proflowers')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1020, 'test20@gmail.com', 'Ken', 'Dat', 'proflowers')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1021, 'test21@gmail.com', 'Ken', 'Dat', 'proflowers')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1022, 'test22@gmail.com', 'Ken', 'Dat', 'proflowers')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1023, 'test23@gmail.com', 'Ken', 'Dat', 'proflowers')
insert into customer (customer_id, email, first_name, last_name, site_id) values (1024, 'test24@gmail.com', 'Ken', 'Dat', 'proflowers')
 
